apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  DB_SERVER: c2VydmVyLWt1YmUtZGFzaGJvYXJkLXN5c3RlbS5kYXRhYmFzZS53aW5kb3dzLm5ldA==
  DB_NAME: ZGF0YWJhc2Uta3ViZS1kYXNoYm9hcmQtc3lzdGVt
  DB_USER: YWRtaW5fa3ViZS1kYXNoYm9hcmQtc3lzdGVt
  DB_PASSWORD: cjAwVDIwMjZJQw==
  SECRET_KEY: c3VwZXJzZWNyZXRrZXk=